# Generated by Django 5.2.6 on 2025-09-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('career_field', models.CharField(blank=True, max_length=100)),
                ('resume_score', models.FloatField(blank=True, null=True)),
                ('skills_missing', models.TextField(blank=True)),
                ('recommended_courses', models.TextField(blank=True)),
            ],
        ),
    ]
